### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by JoelRomero97** [localstack/localstack-demo#44]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/23665094/208509199-2ce49eeb-87cf-43a6-aac0-30e4499cbb8e.png">

I'm able to run the steps listed in [Getting Started](https://docs.localstack.cloud/getting-started/quickstart/#start-your-localstack-container), however, when running `rpm run web` and trying to click on `Create new request` nothing seems to be hapening, receiving the request tho:

<img width="1512" alt="Screenshot 2022-12-19 at 11 57 45 AM" src="https://user-images.githubusercontent.com/23665094/208509401-1040dfdb-fa39-4677-9c14-ce4d55615350.png">

**Comment by andreasciamanna** [comment]
Same here.

I see a bunch of network errors in the console (a bunch because I had the "Auto-refresh" enabled, of course):

```
spread.js:25          GET https://localhost.localstack.cloud:4566/restapis net::ERR_CONNECTION_REFUSED
(anonymous) @ spread.js:25
e.exports @ spread.js:25
e.exports @ spread.js:25
Promise.then (async)
r.request @ spread.js:25
r.<computed> @ spread.js:25
(anonymous) @ index.js:20
getBaseURL @ Inline Babel script:15
render @ Inline Babel script:53
finishClassComponent @ react-dom.development.js:19762
updateClassComponent @ react-dom.development.js:19708
beginWork @ react-dom.development.js:21621
beginWork$1 @ react-dom.development.js:27436
performUnitOfWork @ react-dom.development.js:26567
workLoopSync @ react-dom.development.js:26476
renderRootSync @ react-dom.development.js:26444
performConcurrentWorkOnRoot @ react-dom.development.js:25748
workLoop @ react.development.js:2653
flushWork @ react.development.js:2626
performWorkUntilDeadline @ react.development.js:2920
spread.js:25 Uncaught (in promise) Error: Network Error
    at e.exports (spread.js:25:1)
    at l.onerror (spread.js:25:1)
```

I have started LocalStack with `EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000 localstack start`.

**Comment by whummer** [comment]
Hi @JoelRomero97 @andreasciamanna , thanks for reporting. We have now made a few simplifications/enhancements in the demo app setup - can you please pull the `latest` Docker image and give it another try with the updated instructions in the README? Please keep us posted on how it goes.. Thanks!

**Comment by ta1bbty** [comment]
Hey @whummer 👋 

Thanks for the update. I tried though, it's still not working 🙌 
![image](https://user-images.githubusercontent.com/45117337/217800936-c48c56b7-7b5e-4ac4-96ac-1db5890382e9.png)


I tried the documentation from https://docs.localstack.cloud/getting-started/quickstart/

and also tried the cloud pod method. None of them works 😅 

Regards.
T

**Comment by ta1bbty** [comment]
Also I checked the `package.json` and `Makefile`.
Nor does package.json have `web` as a script nor does `Makefile` have `start` as a script :D 
![image](https://user-images.githubusercontent.com/45117337/217801696-199b4ff9-0a9f-4352-ae4b-62be77ebd5db.png)

**Comment by tinyg210** [comment]
Hi @ta1bbty,  
can you please pull the `latest` Docker image, start LocalStack using `EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000 localstack start` and then run `make install` & `make deploy` in your project's root folder? let me know if that works, please. I just used the same formula, and it's ok. We need to update our docs

**Comment by tinyg210** [comment]
Hi @ta1bbty,
can you please pull the `latest` Docker image, start LocalStack using `localstack start` then run `make install` and `make deploy` in your project's root folder? let me know how it goes. I used the same formula and it works. We need to update our docs.

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up on our last message to see whether your issue has been resolved. Were you able to get it working with the latest version of LocalStack? We would appreciate your feedback!
