### ISSUE TITLE
Deploy and install targets are not working (npm error and bucket not found).

### ISSUE THREAD

**Issue by belmarca** [localstack/localstack-demo#56]
Hi,

I cannot get the demo to work on a fresh install of localstack:

```
2647 verbose stack TypeError: Cannot read properties of null (reading 'pickAlgorithm')
2647 verbose stack     at Integrity.match (/usr/lib/node_modules/npm/node_modules/ssri/lib/index.js:273:24)
2647 verbose stack     at CachePolicy.satisfies (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/policy.js:112:49)
2647 verbose stack     at Function.find (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js:178:25)
2647 verbose stack     at async cacheFetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:8:17)
2647 verbose stack     at async fetch (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
```

```
Error:
Serverless plugin "serverless-deployment-bucket" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-deployment-bucket" to install it.
make: *** [Makefile:14: deploy] Error 1
```

The fix proposed in #55 does not work for me.

```
Linux 4.19.0-23-amd64 #1 SMP Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux
Python 3.10.5
npm v8.19.3
node v16.19.1
```

**Comment by belmarca** [comment]
Bump!

This issue prevents users from completing the [Quickstart](https://docs.localstack.cloud/getting-started/quickstart/).

**Comment by nomadme** [comment]
Same issue happening

**Comment by nomadme** [comment]
Here is the [PR](https://github.com/localstack/localstack-demo/pull/60) that adds additional documentation for those folks having issue with.

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version of the repo? We would appreciate your feedback!

**Comment by josephmcasey** [comment]
Unable to reproduce error
